CLIENT_ID = 'ZMXVCYS3FLV1AV3ZWQ5QWXPB3OSVFGHTABKELSJ1QDJLJRVQ' # your Foursquare ID
CLIENT_SECRET = 'XV2UTOWXTSKFMATY3JMBHRAIPIEOH5MDQCE4SB0O0ZSJHB4L' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version
LIMIT = 100 # A default Foursquare API limit value